version: "2.4"
services:
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    env_file:
      - ${HOME}/.pingidentity/devops
    environment:
      # - VERBOSE=true
      - PING_CONTAINER_UID=1000
      - PING_CONTAINER_GID=1000
      - PING_CONTAINER_PRIVILEGED="false"
      - LDAP_PORT=1389
      - LDAPS_PORT=1636
      - HTTP_PORT=1080
      - HTTPS_PORT=1443
      - JMX_PORT=1689
      - USER_BASE_DN=o=sync
      - SERVER_PROFILE_URL_REDACT="false"
      - SERVER_PROFILE_PD_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
      - SERVER_PROFILE_PARENT=PD
      - SERVER_PROFILE_PD_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_PD_BRANCH=sync_8
      - SERVER_PROFILE_PD_PATH=pd-conf
      - SERVER_PROFILE_PD_PARENT=JOLOKIA
      - SERVER_PROFILE_JOLOKIA_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_JOLOKIA_BRANCH=sync_8
      - SERVER_PROFILE_JOLOKIA_PATH=jolokia-conf
      - SERVER_PROFILE_JOLOKIA_PARENT=SEC
      - SERVER_PROFILE_SEC_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_SEC_BRANCH=sync_8
      - SERVER_PROFILE_SEC_PATH=sec-conf
      - SERVER_PROFILE_SEC_PARENT=SHARED
      - SERVER_PROFILE_SHARED_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_SHARED_BRANCH=sync_8
      - SERVER_PROFILE_SHARED_PATH=shared-conf
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    mem_swappiness: 0
    tmpfs: /run/secrets
    volumes:
      # - ${PWD}/pd-conf:/opt/in
      - /tmp/wk/pd:/opt/out
    ports:
      # export the LDAP prot
      - "5389:1389"
      # export the LDAP TLS port
      - "5636:1636"
      # export the port for JMX traffic
      - "5689:1689"
      # export the  HTTPS port
      - "5443:1443"
    networks:
      - pingnet

  pingdatasync:
    image: pingidentity/pingdatasync:edge
    environment:
      - PING_CONTAINER_UID=1000
      - PING_CONTAINER_GID=1000
      - PING_CONTAINER_PRIVILEGED="false"
      - LDAP_PORT=1389
      - LDAPS_PORT=1636
      - HTTP_PORT=1080
      - HTTPS_PORT=1443
      - JMX_PORT=1689
      - USER_BASE_DN=o=sync
      - SERVER_PROFILE_URL_REDACT="false"
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
      - SERVER_PROFILE_PARENT=JOLOKIA
      - SERVER_PROFILE_JOLOKIA_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_JOLOKIA_BRANCH=sync_8
      - SERVER_PROFILE_JOLOKIA_PATH=jolokia-conf
      - SERVER_PROFILE_JOLOKIA_PARENT=SEC
      - SERVER_PROFILE_SEC_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_SEC_BRANCH=sync_8
      - SERVER_PROFILE_SEC_PATH=sec-conf
      - SERVER_PROFILE_SEC_PARENT=SHARED
      - SERVER_PROFILE_SHARED_URL=https://github.com/arnaudlacour/server-profile-pingdirerctory-jolokia.git
      - SERVER_PROFILE_SHARED_BRANCH=sync_8
      - SERVER_PROFILE_SHARED_PATH=shared-conf
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "2636:636"
      - "2443:443"
    networks:
      - pingnet
    volumes:
      - /tmp/wk/sync:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/simple-sync/pingdatasync:/opt/in

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    environment:
      - HTTP_PORT=6080
      - HTTPS_PORT=6443
    ports:
      - "6080:6080"
      - "6443:6443"
    networks:
      - pingnet

networks:
    pingnet:
